### ISSUE TITLE
glfw/glfw

### ISSUE THREAD

**Issue by tarik02** [LoopPerfect/buckaroo-wishlist#129]
Does not work. I get an error: "No supported window creation API selected"

**Comment by njlr** [comment]
Which platform?

**Comment by tarik02** [comment]
@njlr, Win32

**Comment by tarik02** [comment]
There's something strange. There is branch 'buck/3.2.1', it has bigger ['BUCK'](https://github.com/buckaroo-pm/glfw/blob/buck/3.2.1/BUCK) than [master's one](https://github.com/buckaroo-pm/glfw/blob/master/BUCK), while the first does not have 'buckaroo.toml' at all.

**Comment by tarik02** [comment]
https://github.com/buckaroo-pm/glfw/pull/1
