### ISSUE TITLE
Where is the full package list ?

### ISSUE THREAD

**Issue by ar90n** [LoopPerfect/buckaroo-wishlist#55]
I want to check the available packages.
README.md show s that the full list of packages can be found at buckaroo.pm. 
But I can only see the most popular packages.
Where can I find it ?

**Comment by njlr** [comment]
You have two options: 
 * First, you can search for `*` on Buckaroo.pm: [https://buckaroo.pm/search?q=*](https://buckaroo.pm/search?q=*)
 * Second, you can browse the [official cookbook on GitHub](https://github.com/LoopPerfect/buckaroo-recipes)

If there is a package you are looking for but cannot find, please [make an issue on this repo](https://github.com/LoopPerfect/buckaroo-wishlist/issues/new) and we will port it ASAP. 

Hope that helps!

**Comment by ar90n** [comment]
Hi njlr.
Thanks for your advices.
I could see available packages.

Buckaroo is the great solution I want.
I'm willing to use it in my projects.
