### ISSUE TITLE
gabime/spdlog

### ISSUE THREAD

**Issue by d53dave** [LoopPerfect/buckaroo-wishlist#56]
[gabime/spdlog](https://github.com/gabime/spdlog)
Logging Library

**Comment by njlr** [comment]
Hi @d53dave. Taking a look now - seems to be header-only so shouldn't be too hard!

**Comment by d53dave** [comment]
Awesome. Looking forward to ditching CMake.

**Comment by njlr** [comment]
[PR](https://github.com/LoopPerfect/buckaroo-recipes/pull/65)

**Comment by njlr** [comment]
Done. To install: 

```
buckaroo upgrade 
buckaroo install gabime/spdlog 
```
