### ISSUE TITLE
sigrok/libserialport

### ISSUE THREAD

**Issue by Nixes** [LoopPerfect/buckaroo-wishlist#64]
source: git://sigrok.org/libserialport

Very simple build, no dependencies.

**Comment by njlr** [comment]
Hi @Nixes, taking a look now.

**Comment by njlr** [comment]
I have added `sigrok/serialport` to the official cookbook. It has been tested on macOS Sierra and Ubuntu 17. 

To install it: 

```bash=
buckaroo install sigrok/serialport
```

Note that the current version wraps the existing autotools setup for generating `config.h` and so on. As such, cross-compilation will probably not work. If that is a requirement let me know! 

If you are on macOS, you may need to add some frameworks to your application when using `libserialport`: 

```python=
  linker_flags = [
    '-framework', 'CoreFoundation',
    '-framework', 'IOKit',
  ]
```
