### ISSUE TITLE
google/protobuf

### ISSUE THREAD

**Issue by nicht** [LoopPerfect/buckaroo-wishlist#66]
[google/protobuf](https://github.com/google/protobuf)

Please, can you take a look at it? Thanks.

EDIT: I need protobuf for Linux and Windows, but if you can only make it for linux its totally fine.

**Comment by njlr** [comment]
Hi @nicht taking a look now. I will ensure that the port works for Linux, but Windows may take some time. The Buck team are still working on the VC++ integration with Buck.

**Comment by nicht** [comment]
Cool. Thank you so much <3
