### ISSUE TITLE
g-truc/glm

### ISSUE THREAD

**Issue by CouleeApps** [LoopPerfect/buckaroo-wishlist#67]
Source: https://github.com/g-truc/glm
Header-only library

**Comment by njlr** [comment]
Hi @CouleeApps I'll take a look at this today.

**Comment by njlr** [comment]
I have written the Buck files for glm: [PR](https://github.com/g-truc/glm/pull/663)

Adding it to the Buckaroo cookbook now...

**Comment by njlr** [comment]
It looks like glm uses non-standard versioning for its releases (4 digits, e.g. `0.9.8.4`). I will work to add support for this in Buckaroo (https://github.com/LoopPerfect/buckaroo/issues/108)

In the meantime, you can use glm `v0.9.8.4` directly from my fork: 

```bash=
buckaroo install github+njlr/glm
```

**Comment by njlr** [comment]
The GLM maintainers have rejected the [PR](https://github.com/g-truc/glm/pull/663) 😞 but we can add it to the Buckaroo cookbook anyway (https://github.com/LoopPerfect/buckaroo-recipes/pull/76). 

This recipe will require Buckaroo v1.3.1+
