### ISSUE TITLE
mongocxx

### ISSUE THREAD

**Issue by ogranada** [LoopPerfect/buckaroo-wishlist#69]
mongodb/mongo-cxx-driver

Driver for MongoDB.

[github.com/mongodb/mongo-cxx-driver](https://github.com/mongodb/mongo-cxx-driver).

**Comment by njlr** [comment]
Hi @ogranada I am taking a look now. 

I have already ported the first dependency of `mongo-cxx-driver`, which is [bson](https://github.com/njlr/bson/tree/buck/1.7.0).

**Comment by ogranada-xk** [comment]
WoW, thanks 👍

**Comment by njlr** [comment]
There is a port here: https://github.com/buckaroo-pm/mongo-cxx-driver

Currently only tested on Linux. 

```bash
buckaroo add 'github.com/buckaroo-pm/mongo-cxx-driver@branch=master'
```
