### ISSUE TITLE
ThrowTheSwitch/Unity

### ISSUE THREAD

**Issue by karlding** [LoopPerfect/buckaroo-wishlist#79]
I'd love to see support for [ThrowTheSwitch/Unity](https://github.com/ThrowTheSwitch/Unity)!

**Comment by njlr** [comment]
This would certainly be possible, but have you thought about using Google Test? It has some integration with Buck build itself, allowing for test caching and so on. https://buckbuild.com/rule/cxx_test.html

**Comment by njlr** [comment]
https://github.com/LoopPerfect/buckaroo-recipes/pull/108
