### ISSUE TITLE
nanopb/nanopb

### ISSUE THREAD

**Issue by karlding** [LoopPerfect/buckaroo-wishlist#80]
Having an embedded-friendly implementation of protobufs (namely [nanopb/nanopb](https://github.com/nanopb/nanopb)) would be nice.

It has bazel support, so it shouldn't be too bad to port over?

**Comment by njlr** [comment]
Hi @karlding I am taking a look now.

**Comment by njlr** [comment]
https://github.com/LoopPerfect/buckaroo-recipes/pull/107
