### ISSUE TITLE
curl/curl

### ISSUE THREAD

**Issue by toulouse** [LoopPerfect/buckaroo-wishlist#86]
https://github.com/curl/curl
any version (latest tagged seems to be curl-7_57_0)

I'm on OS X, and I don't install homebrew. Dependencies could get interesting with Nghttp2+openssl(or native SSL)+ldap+zlib+libSSH2+... -- though I personally don' plan to exercise all of those currently, for now I mostly want to make web requests.

**Comment by njlr** [comment]
Current solution is this "wrapper" package: https://github.com/buckaroo-pm/pkg-config-curl

**Comment by njlr** [comment]
We now have a proper package also: https://github.com/buckaroo-pm/curl
