### ISSUE TITLE
Please rebase Flatbuffers & Snappy!

### ISSUE THREAD

**Issue by Nickersoft** [LoopPerfect/buckaroo-wishlist#87]
The latest version of `flatc` (1.8) is incompatible with the Buckaroo version of Flatbuffers (1.6). It should be at least 1.7.1 (though the current version is 1.8+ I think). Also, the Snappy version is behind as well. Please rebase. Thanks.

**Comment by njlr** [comment]
Latest snappy port is here: https://github.com/buckaroo-pm/google-snappy

Flatbuffers is next. 

We are currently working on automating the process of new releases.

**Comment by njlr** [comment]
Flatbuffers: https://github.com/buckaroo-pm/google-flatbuffers
