### ISSUE TITLE
Microsoft/cpprestsdk

### ISSUE THREAD

**Issue by karlding** [LoopPerfect/buckaroo-wishlist#89]
It would be nice to support Microsoft's [C++ REST SDK](https://github.com/Microsoft/cpprestsdk).

**Comment by njlr** [comment]
There is a Buckaroo port here: https://github.com/buckaroo-pm/microsoft-cpprestsdk

```bash=
buckaroo add github.com/buckaroo-pm/microsoft-cpprestsdk@branch=master
```
