### ISSUE TITLE
jedisct1/libsodium (1.0.16)

### ISSUE THREAD

**Issue by matteomonti** [LoopPerfect/buckaroo-wishlist#93]
This one should be easy: `jedisct1/libsodium` is already available from [buckaroo.pm](buckaroo.pm), but the version currently available is `1.0.11`. 

Many improvements have been done since then, and my code relies on some of the more recently introduced features. Is it possible to add a more recent version? `1.0.16` would be perfect.

Thank you! 😃

**Comment by matteomonti** [comment]
Any news on that? Is anyone still working on this repo?

**Comment by njlr** [comment]
New version released.
