### ISSUE TITLE
cinemast/libjson-rpc-cpp

### ISSUE THREAD

**Issue by Mohamed-G-Abdelhady** [LoopPerfect/buckaroo-wishlist#94]
https://github.com/cinemast/libjson-rpc-cpp
v1.1.0
Linux x86_64 &  i386

**Comment by njlr** [comment]
There is a Buckaroo package here: https://github.com/buckaroo-pm/cinemast-libjson-rpc-cpp

```bash=
buckaroo add github.com/buckaroo-pm/cinemast-libjson-rpc-cpp@branch=master
```
