### ISSUE TITLE
https://www.buckaroo.pm/ SSL certificate issue

### ISSUE THREAD

**Issue by hartwork** [LoopPerfect/buckaroo-wishlist#98]
Hi!

Is this the right place to report to? It seems like https://www.buckaroo.pm/ with `www.` is linked from the readme but has a broken SSL certificate. Could someone have a look?

Thanks and best, Sebastian

**Comment by nikhedonia** [comment]
cheers, we'll have a look

**Comment by njlr** [comment]
Now we redirect to GitHub.
